image: newcity/builder:latest

#from: https://nicolaw.uk/GitLabCiPushingWrites
variables:
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i .ssh/id_rsa-gitlab-ci"
  GIT_STRATEGY: clone
  temporary_branch: "gitlab-ci"
  REMOTE_REPO: git@gitlab.com:uky-web/patternlab-artifact.git
  BUILD_REPO: /tmp/pl-artifact

before_script:
#- eval $(ssh-agent -s)
#- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
##- mkdir -p ~/.ssh
##- chmod 700 ~/.ssh


stages:
- build
- deploy

compile:assets:
  stage: build
  script:
  - cp docker/taskrunner/* .
  - npm install
  - gulp build-all
  artifacts:
    paths:
    - dist
    expire_in: 1 week
#  only:
#  - master

push:artifact:
  stage: deploy
  script:
  # Setup ssh
  - mkdir -pvm 0700 .ssh
  - echo "$SSH_PRIVATE_KEY" > .ssh/id_rsa-gitlab-ci
  - chmod 0400 .ssh/id_rsa-gitlab-ci

  # Prepare git for pushing back to repository.
  - git clone $REMOTE_REPO $BUILD_REPO
#  - cd $BUILD_REPO
  - git checkout -b "$temporary_branch"
  - git config --global user.email "uky-web-ci@uky.edu"
  - git config --global user.name "UKY Web CI Bot"
  #- git remote set-url --push origin $(perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#' <<< $REMOTE_REPO)

  # Add changes from build
  - rsync -av --delete --exclude .git dist/* $BUILD_REPO
  - cd $BUILD_REPO
  - git add *
  - git commit -am "Autogenerated at revision $CI_COMMIT_SHA [skip ci]"  || true

  #push back to the repository
  - git push -u origin "$temporary_branch:$CI_COMMIT_REF_NAME" || true
#
#  artifacts:
#    paths:
#    - pl/public

#    only:
#       - master


#generate:patternlab:
#  image: newcity/pl-bash:latest
#  stage: combine
#  script:
#    - mv /pl pl
#    - rm -rf pl/source/*
#    - cp -R src/* pl/source/
#    - cd pl && php core/console --generate
#    - cd .. && rsync -ra dist/* pl/public/
#  artifacts:
#    paths:
#      - dist
#      - pl/public
#    expire_in: 1 week
#  only:
#     - master
#
#push:
#  stage: deploy
#  script:
#    - cp docker/pl/Makefile .
#    - make init
#    - make clone
#    - make replay
#    - make push
#  artifacts:
#    paths:
#      - pl/public
#  only:
#     - master
#
#pa11y:
#  before_script:
#    - echo "Did you know the 'a11y' abbreviation is considered inaccessable? It's true."
#  stage: accessibility
#  image: newcity/pa11y-sh:jhw-config
#  script:
#    - pwd
#    - ls -alh /home/chrome
#    - pa11y-ci --config /home/chrome/.pa11yci -s https://newcity.gitlab.io/uk-d8-patternlab-artifact/xml/sitemap.xml
#  only:
#    - master
