---
image: newcity/builder:latest

before_script:
  # make all submodule references relative and bring them up to date
  #- sed -i 's/git@gitlab.com:newcity/..\/../g' .gitmodules
  #- git submodule sync --recursive
  #- git submodule update --init --recursive
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$GITHUB_PATTERNLAB_PRIVATE_KEY")

stages:
  - build
  - combine
  - deploy

compile:assets:
  stage: build
  script:
    - cp docker/taskrunner/* .
    - npm install
    - gulp build-all
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  only:
     - master

generate:patternlab:
  image: newcity/pl-bash:latest
  stage: combine
  script:
    - mv /pl pl
    - rm -rf pl/source/*
    - rsync -rva dist/* pl/source/
    - ls -alH pl/source
    - cp -R src/* pl/source/
    - cd pl && php core/console --generate
    - ls -alH pl/public
  artifacts:
    paths:
      - dist
      - pl/public
    expire_in: 1 week
  only:
     - master

push:
  stage: deploy
  script:
    - cp docker/pl/Makefile .
    - make init
    - make clone
    - make replay
    # make push
  artifacts:
    paths:
      - pl/public
  only:
     - master