---
image: newcity/builder:latest

before_script:
  # make all submodule references relative and bring them up to date
  #- sed -i 's/git@gitlab.com:newcity/..\/../g' .gitmodules
  #- git submodule sync --recursive
  #- git submodule update --init --recursive
  #- eval $(ssh-agent -s)
  #- ssh-add <(echo "$GITLAB_BUILD_KEY")

stages:
  - build
  - combine
  - deploy
  - accessibility

compile:assets:
  stage: build
  script:
    - cp docker/taskrunner/* .
    - npm install
    - gulp build-all
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  only:
     - master

generate:patternlab:
  image: newcity/pl-bash:latest
  stage: combine
  script:
    - mv /pl pl
    - rm -rf pl/source/*
    - cp -R src/* pl/source/
    - cd pl && php core/console --generate
    - cd .. && rsync -ra dist/* pl/public/
  artifacts:
    paths:
      - dist
      - pl/public
    expire_in: 1 week
  only:
     - master

push:
  stage: deploy
  script:
    - cp docker/pl/Makefile .
    - make init
    - make clone
    - make replay
    - make push
  artifacts:
    paths:
      - pl/public
  only:
     - master

pa11y:
  before_script:
    - echo "Did you know the 'a11y' abbreviation is considered inaccessable? It's true."
  stage: accessibility
  image: newcity/pa11y-sh:jhw-config
  script:
    - pwd
    - ls -alh /home/chrome
    - pa11y-ci --config /home/chrome/.pa11yci -s https://newcity.gitlab.io/uk-d8-patternlab-artifact/xml/sitemap.xml
  only:
    - master
