---
image: newcity/builder:latest

before_script:
  - sed -i 's/git@gitlab.com:newcity/..\/../g' .gitmodules
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - build
  - combine
  - deploy

compile:assets:
  stage: build
  script:
    - cp docker/taskrunner/* .
    - npm install
    - gulp build-all
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  only:
     - master

generate:patternlab:
  image: newcity/pl-bash:latest
  stage: combine
  script:
    - mv /pl pl
    - rm -rf pl/source/*
    - cp -R dist/* pl/source/
    - cp -R src/* pl/source/
    - cd pl && php core/console --generate
  artifacts:
    paths:
      - dist
      - pl/public
    expire_in: 1 week
  only:
     - master

push:
  stage: deploy
  script:
    - make init
    - make clone
    - make replay
    - make push
  only:
     - master