# 

files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  indentation: 
    - size: 2
  empty-line-between-blocks:
    - include: false
  bem-depth :
    - max-depth: 1
  class-name-format: 0
  id-name-format: 0
  indentation:
     - size: 2
  leading-zero:
    - 1
    - include: true
  nesting-depth:
    - 1
    - max-depth: 3
  no-css-comments: 0
  no-extends: 1
  no-qualifying-elements: 0
  placeholder-in-extend: 0
  placeholder-name-format: 0
